### PR TITLE
Update youtube_channel_info.txt

### PR DESCRIPTION
**Pull request by rickyyhi5**

### CODE REVIEW

**Comment by rickyyhi5** [comment]
Hi, is pull request not allowed??

**Comment by naveenland4** [comment]
Added bro.... But not sur it will pick the m3u8 link from live stream... Some live streams are encrypted which our script doesnot support. thanks.

**Comment by rickyyhi5** [comment]
Seems like it is encrypted link, it's not working, thq btw i had few channels list (only 10-20 english), is ur script is capable add those?

**Comment by naveenland4** [comment]
Pls provide the links ill add it with the  Logos....

**Comment by rickyyhi5** [comment]
Did u had any discord channel or telegraph?

**Pull request closed without merging**
